stages:
  serverConfig:
    - from:
        image: golang:latest
        as: golang
    - env:
        GOMODULE: on
        GOFLAGS: -mod=vendor
    - copy:
        basedir: .
        destdir: /code-runner
    - workdir:
        dir: /code-runner
    - runCommand:
        param: go build -o code-runner-server
    - serverPort:
        number: 8082
    - cmd:
        params:
          - ./code-runner-server