serverConfig:
  from: golang
  env:
    GOMODULE: on
    GOFLAGS: -mod=vendor
  copy:
    baseDir: .
    destDir: /code-runner
  workdir: /code-runner
  run: make
  serverPort: 8082
  cmd: ./code-runner-server

# TODO: assignment config
