name: Build and Test Image Builder
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
    - name: Golang Setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.9
      id: go

    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Get Dependencies using Go Modules
      run: make dependency

    - name: Build Image Builder
      run: make
      
    - name: Test Image Builder
      run: go test ./...
      timeout-minutes: 2
